export const SET_NAME = 'SET_NAME';

export const SET_ACCESS_ID = 'SET_ACCESS_ID';

export const SET_USER = 'SET_USER';

export const SET_SIGNED_IN = 'SET_SIGNED_IN';

export const SET_USER_IMAGE_NAME = 'SET_USER_IMAGE_NAME';

// snack bar
export const TOGGLE_SNACK_BAR = 'TOGGLE_SNACK_BAR';

export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
export const SET_SELECTED_SUB_CATEGORY = 'SET_SELECTED_SUB_CATEGORY';

export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_SELECTED_ADDRESS = 'SET_SELECTED_ADDRESS';
export const SET_ADDRESS_ACTION = 'SET_ADDRESS_ACTION';

// sign in modal
export const SHOW_SIGNIN_MODAL = 'SHOW_SIGNIN_MODAL';
export const HIDE_SIGNIN_MODAL = 'HIDE_SIGNIN_MODAL';

// favourites

export const ADD_TO_FAVOURITES = 'ADD_TO_FAVOURITES';
export const REMOVE_FROM_FAVOURITES = 'REMOVE_FROM_FAVOURITES';
export const SET_LATEST_ADDED_FAVOURITE_PRODUCT =
  'SET_LATEST_ADDED_FAVOURITE_PRODUCT';

export const SHOULD_HOME_SCREEN_REFRESH = 'SHOULD_HOME_SCREEN_REFRESH';
